## Python assignment1
- Inspecting structure: shape, dtypes, info, head, tail
- Summary stats: describe, nunique
- Missing values: isna, fillna (median/mean imputation)
- Selecting columns/rows: lists, iloc, boolean masks, isin
- Filtering with conditions and ranges 
- Sorting by multiple columns
- Duplicates: duplicated, drop_duplicates
- Derived columns & categorization: arithmetic, pd.cut
- Groupby & aggregation: agg, boolean-to-int counting
- (Optional) quick sanity plots

In [1]:
import pandas as pd
import numpy as np
from pydataset import data

In [2]:
df= data('airquality')

In [3]:
df.shape

(153, 6)

In [4]:
df.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Temp         int64
Month        int64
Day          int64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 153 entries, 1 to 153
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    116 non-null    float64
 1   Solar.R  146 non-null    float64
 2   Wind     153 non-null    float64
 3   Temp     153 non-null    int64
 4   Month    153 non-null    int64
 5   Day      153 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 8.4 KB

In [6]:
df.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [7]:
df.tail()

     Ozone  Solar.R  Wind  Temp  Month  Day
149   30.0    193.0   6.9    70      9   26
150    NaN    145.0  13.2    77      9   27
151   14.0    191.0  14.3    75      9   28
152   18.0    131.0   8.0    76      9   29
153   20.0    223.0  11.5    68      9   30

In [8]:
df.columns

Index(['Ozone', 'Solar.R', 'Wind', 'Temp', 'Month', 'Day'], dtype='object')

In [10]:
df.describe()

            Ozone     Solar.R        Wind        Temp       Month         Day
count  116.000000  146.000000  153.000000  153.000000  153.000000  153.000000
mean    42.129310  185.931507    9.957516   77.882353    6.993464   15.803922
std     32.987885   90.058422    3.523001    9.465270    1.416522    8.864520
min      1.000000    7.000000    1.700000   56.000000    5.000000    1.000000
25%     18.000000  115.750000    7.400000   72.000000    6.000000    8.000000
50%     31.500000  205.000000    9.700000   79.000000    7.000000   16.000000
75%     63.250000  258.750000   11.500000   85.000000    8.000000   23.000000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000

In [14]:
df.nunique()

Ozone       67
Solar.R    117
Wind        31
Temp        40
Month        5
Day         31
dtype: int64

In [15]:
df.isnull()

     Ozone  Solar.R   Wind   Temp  Month    Day
1    False    False  False  False  False  False
2    False    False  False  False  False  False
3    False    False  False  False  False  False
4    False    False  False  False  False  False
5     True     True  False  False  False  False
6    False     True  False  False  False  False
7    False    False  False  False  False  False
8    False    False  False  False  False  False
9    False    False  False  False  False  False
10    True    False  False  False  False  False
11   False     True  False  False  False  False
12   False    False  False  False  False  False
13   False    False  False  False  False  False
14   False    False  False  False  False  False
15   False    False  False  False  False  False
16   False    False  False  False  False  False
17   False    False  False  False  False  False
18   False    False  False  False  False  False
19   False    False  False  False  False  False
20   False    False  False  False  False  False
21   False    False  False  False  False  False
22   False    False  False  False  False  False
23   False    False  False  False  False  False
24   False    False  False  False  False  False
25    True    False  False  False  False  False
26    True    False  False  False  False  False
27    True     True  False  False  False  False
28   False    False  False  False  False  False
29   False    False  False  False  False  False
30   False    False  False  False  False  False
31   False    False  False  False  False  False
32    True    False  False  False  False  False
33    True    False  False  False  False  False
34    True    False  False  False  False  False
35    True    False  False  False  False  False
36    True    False  False  False  False  False
37    True    False  False  False  False  False
38   False    False  False  False  False  False
39    True    False  False  False  False  False
40   False    False  False  False  False  False
41   False    False  False  False  False  False
42    True    False  False  False  False  False
43    True    False  False  False  False  False
44   False    False  False  False  False  False
45    True    False  False  False  False  False
46    True    False  False  False  False  False
47   False    False  False  False  False  False
48   False    False  False  False  False  False
49   False    False  False  False  False  False
50   False    False  False  False  False  False
51   False    False  False  False  False  False
52    True    False  False  False  False  False
53    True    False  False  False  False  False
54    True    False  False  False  False  False
55    True    False  False  False  False  False
56    True    False  False  False  False  False
57    True    False  False  False  False  False
58    True    False  False  False  False  False
59    True    False  False  False  False  False
60    True    False  False  False  False  False
61    True    False  False  False  False  False
62   False    False  False  False  False  False
63   False    False  False  False  False  False
64   False    False  False  False  False  False
65    True    False  False  False  False  False
66   False    False  False  False  False  False
67   False    False  False  False  False  False
68   False    False  False  False  False  False
69   False    False  False  False  False  False
70   False    False  False  False  False  False
71   False    False  False  False  False  False
72    True    False  False  False  False  False
73   False    False  False  False  False  False
74   False    False  False  False  False  False
75    True    False  False  False  False  False
76   False    False  False  False  False  False
77   False    False  False  False  False  False
78   False    False  False  False  False  False
79   False    False  False  False  False  False
80   False    False  False  False  False  False
81   False    False  False  False  False  False
82   False    False  False  False  False  False
83    True    False  False  False  False  False
84    True    False  False  False  False  False
85   False    False  False  False  False  False
86   False    False  False  False  False  False
87   False    False  False  False  False  False
88   False    False  False  False  False  False
89   False    False  False  False  False  False
90   False    False  False  False  False  False
91   False    False  False  False  False  False
92   False    False  False  False  False  False
93   False    False  False  False  False  False
94   False    False  False  False  False  False
95   False    False  False  False  False  False
96   False     True  False  False  False  False
97   False     True  False  False  False  False
98   False     True  False  False  False  False
99   False    False  False  False  False  False
100  False    False  False  False  False  False
101  False    False  False  False  False  False
102   True    False  False  False  False  False
103   True    False  False  False  False  False
104  False    False  False  False  False  False
105  False    False  False  False  False  False
106  False    False  False  False  False  False
107   True    False  False  False  False  False
108  False    False  False  False  False  False
109  False    False  False  False  False  False
110  False    False  False  False  False  False
111  False    False  False  False  False  False
112  False    False  False  False  False  False
113  False    False  False  False  False  False
114  False    False  False  False  False  False
115   True    False  False  False  False  False
116  False    False  False  False  False  False
117  False    False  False  False  False  False
118  False    False  False  False  False  False
119   True    False  False  False  False  False
120  False    False  False  False  False  False
121  False    False  False  False  False  False
122  False    False  False  False  False  False
123  False    False  False  False  False  False
124  False    False  False  False  False  False
125  False    False  False  False  False  False
126  False    False  False  False  False  False
127  False    False  False  False  False  False
128  False    False  False  False  False  False
129  False    False  False  False  False  False
130  False    False  False  False  False  False
131  False    False  False  False  False  False
132  False    False  False  False  False  False
133  False    False  False  False  False  False
134  False    False  False  False  False  False
135  False    False  False  False  False  False
136  False    False  False  False  False  False
137  False    False  False  False  False  False
138  False    False  False  False  False  False
139  False    False  False  False  False  False
140  False    False  False  False  False  False
141  False    False  False  False  False  False
142  False    False  False  False  False  False
143  False    False  False  False  False  False
144  False    False  False  False  False  False
145  False    False  False  False  False  False
146  False    False  False  False  False  False
147  False    False  False  False  False  False
148  False    False  False  False  False  False
149  False    False  False  False  False  False
150   True    False  False  False  False  False
151  False    False  False  False  False  False
152  False    False  False  False  False  False
153  False    False  False  False  False  False

AttributeError: 'function' object has no attribute 'sum'