## conect mysql to python

In [8]:
import pandas as pd
from sqlalchemy import create_engine
#conn = mysql.connector.connect( host='localhost', user='root', password='piit2025', database='dup')
conn = create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")
conn

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [15]:
empQ = "SELECT * FROM emp"
empdf = pd.read_sql(empQ, conn)
empdf.head()

   empno   ename       job     mgr    hiredate     sal   comm  deptno
0   1234  DHIRAJ   ANALYST  7839.0  1988-12-17  5000.0  100.0      10
1   1324    SHAN   ANALYST  7839.0  1988-12-17  4000.0   50.0      10
2   7369   SMITH     CLERK  7902.0  1980-12-17   800.0    NaN      20
3   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0      30
4   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0  500.0      30

In [11]:
deptQ = "SELECT * FROM dept"
deptdf = pd.read_sql(deptQ, conn)
deptdf.head()

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [13]:
emp_dept = pd.merge(empdf, deptdf, on = 'deptno')
emp_dept

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,SALES,CHICAGO
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,ACCOUNTING,NEW YORK
9,7788,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20,RESEARCH,DALLAS
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
12,7876,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20,RESEARCH,DALLAS
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK